# Generated by Django 4.2.3 on 2023-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customuser_username_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
