# Generated by Django 4.2.3 on 2023-07-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_category_cat_image_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
