# Generated by Django 4.2.3 on 2023-08-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_customuser_name_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
