# Generated by Django 4.2.3 on 2023-08-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customuser_date_joined_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
