# Generated by Django 4.2.3 on 2023-08-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
