# Generated by Django 4.2.3 on 2023-08-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
